[package]
name = "Sealdatasampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "sealdatasampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tseal = { path = "../../../sgx_tseal" }
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_rand = { path = "../../../sgx_rand" }
serde = { path = "../../../third_party/serde-rs/serde/serde" }
serde_derive = { path = "../../../third_party/serde-rs/serde/serde_derive" }
serde_cbor = { path = "../../../third_party/cbor" }
